---
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-cfg
data:
  aio-vswitch.json: |
{{ include "network-cfg.aio-vswitch" . | indent 4 }}

  aio-kiknos.json: |
{{ include "network-cfg.aio-kiknos" . | indent 4 }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: network-cfg-job
spec:
  template:
    spec:
      containers:
        - name: network-config
          image: {{ .Values.aio.image.repository }}:{{ .Values.aio.image.tag }}
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              /usr/bin/kiknosctl --config-dir=/var/kiknosctl --service-label=$NODE_NAME import /var/cfg/aio-vswitch.json && \
              /usr/bin/kiknosctl --config-dir=/var/kiknosctl --service-label={{ .Values.aio.serviceLabel }} import /var/cfg/aio-kiknos.json
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: kiknosctl-config
              mountPath: /var/kiknosctl
            - name: network-config
              mountPath: /var/cfg
            {{- if .Values.etcd.secureTransport }}
            - name: etcd-secrets
              mountPath: /var/etcd/secrets
            {{- end }}
      volumes:
        - name: kiknosctl-config
          configMap:
            name: kiknosctl-job-cfg
        - name: network-config
          configMap:
            name: network-cfg
        {{- if .Values.etcd.secureTransport }}
        - name: etcd-secrets
          secret:
            secretName: {{ .Values.etcd.secrets.secretName }}
        {{- end }}
      restartPolicy: OnFailure
  backoffLimit: 10
